Ext.define('iFlat.model.bi.ProjectSchedule', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'projectSchedule.id', mapping: 'id', type: 'string'},
        {name: 'projectSchedule.projNo', mapping: 'projNo', type: 'string'},
        {name: 'projectSchedule.commencePln', mapping: 'commencePln', type: 'date',},
        {name: 'projectSchedule.commenceAct', mapping: 'commenceAct', type: 'date',},
        {name: 'projectSchedule.shipwayPln', mapping: 'shipwayPln', type: 'date'},
        {name: 'projectSchedule.shipwayAct', mapping: 'shipwayAct', type: 'date'},
        {name: 'projectSchedule.launchPln', mapping: 'launchPln', type: 'date'},
        {name: 'projectSchedule.launchAct', mapping: 'launchAct', type: 'date'},
        {name: 'projectSchedule.seaTrialPln', mapping: 'seaTrialPln', type: 'date'},
        {name: 'projectSchedule.seaTrialAct', mapping: 'seaTrialAct', type: 'date'},
        {name: 'projectSchedule.deliveryPln', mapping: 'deliveryPln', type: 'date'},
        {name: 'projectSchedule.deliveryAct', mapping: 'deliveryAct', type: 'date'},
        {name: 'projectSchedule.blockPrdPln', mapping: 'blockPrdPln', type: 'number'},
        {name: 'projectSchedule.blockPrdAct', mapping: 'blockPrdAct', type: 'number'},
        {name: 'projectSchedule.shipwayPrdPln', mapping: 'shipwayPrdPln', type: 'number'},
        {name: 'projectSchedule.shipwayPrdAct', mapping: 'shipwayPrdAct', type: 'number'},
        {name: 'projectSchedule.dockPrdPln', mapping: 'dockPrdPln', type: 'number'},
        {name: 'projectSchedule.dockPrdAct', mapping: 'dockPrdAct', type: 'number'},
        {name: 'projectSchedule.buildPrdPln', mapping: 'buildPrdPln', type: 'number'},
        {name: 'projectSchedule.buildPrdAct', mapping: 'buildPrdAct', type: 'number'},
        {name: 'projectSchedule.month', mapping: 'month', type: 'date'},
        {name: 'projectSchedule.fixed', mapping: 'fixed', type: 'date'},
        {name: 'projectSchedule.version', mapping: 'version', type: 'number'},
    ]
});