Ext.define('iFlat.model.bi.ProjectInProcessInfo', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'projectInProcessInfo.id', mapping: 'id', type: 'string'},
        {name: 'projectInProcessInfo.projNo', mapping: 'projNo', type: 'string'},
        {name: 'projectInProcessInfo.type', mapping: 'type', type: 'string'},
        {name: 'projectInProcessInfo.target', mapping: 'target', type: 'number' },
        {name: 'projectInProcessInfo.actual', mapping: 'actual', type: 'number' },
        {name: 'projectInProcessInfo.difference', mapping: 'difference', type: 'number' },
        {name: 'projectInProcessInfo.diffPct',
            mapping: function (data) {
                return data.diffPct.toFixed(2);
            },
            type: 'number' },
        {name: 'projectInProcessInfo.month', mapping: 'month', type: 'date' },
        {name: 'projectInProcessInfo.version', mapping: 'version', type: 'number' },
        {name: 'projectInProcessInfo.code', mapping: 'code', type: 'string'},
        {name: 'projectInProcessInfo.name', mapping: 'name', type: 'string'},
        {name: 'projectInProcessInfo.shortName', mapping: 'shortName', type: 'string'},
        {name: 'projectInProcessInfo.plannedPlace', mapping: 'plannedPlace', type: 'string'},
        {name: 'projectInProcessInfo.actualPlace', mapping: 'actualPlace', type: 'string'},
        {name: 'projectInProcessInfo.commencePln', mapping: 'commencePln', type: 'date',},
        {name: 'projectInProcessInfo.commenceAct', mapping: 'commenceAct', type: 'date',},
        {name: 'projectInProcessInfo.shipwayPln', mapping: 'shipwayPln', type: 'date'},
        {name: 'projectInProcessInfo.shipwayAct', mapping: 'shipwayAct', type: 'date'},
        {name: 'projectInProcessInfo.launchPln', mapping: 'launchPln', type: 'date'},
        {name: 'projectInProcessInfo.launchAct', mapping: 'launchAct', type: 'date'},
        {name: 'projectInProcessInfo.seaTrialPln', mapping: 'seaTrialPln', type: 'date'},
        {name: 'projectInProcessInfo.seaTrialAct', mapping: 'seaTrialAct', type: 'date'},
        {name: 'projectInProcessInfo.deliveryPln', mapping: 'deliveryPln', type: 'date'},
        {name: 'projectInProcessInfo.deliveryAct', mapping: 'deliveryAct', type: 'date'},
        {name: 'projectInProcessInfo.blockPrdPln', mapping: 'blockPrdPln', type: 'number'},
        {name: 'projectInProcessInfo.blockPrdAct', mapping: 'blockPrdAct', type: 'number'},
        {name: 'projectInProcessInfo.shipwayPrdPln', mapping: 'shipwayPrdPln', type: 'number'},
        {name: 'projectInProcessInfo.shipwayPrdAct', mapping: 'shipwayPrdAct', type: 'number'},
        {name: 'projectInProcessInfo.dockPrdPln', mapping: 'dockPrdPln', type: 'number'},
        {name: 'projectInProcessInfo.dockPrdAct', mapping: 'dockPrdAct', type: 'number'},
        {name: 'projectInProcessInfo.buildPrdPln', mapping: 'buildPrdPln', type: 'number'},
        {name: 'projectInProcessInfo.buildPrdAct', mapping: 'buildPrdAct', type: 'number'},
    ]
});
