Ext.define('iFlat.model.sm.SrSettlementDetlFirst', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'srSettlementDetlFirst.id', mapping: 'id', type: 'string'},
        {name: 'srSettlementDetlFirst.pid', mapping: 'pid', type: 'string'},
        {name: 'srSettlementDetlFirst.type', mapping: 'type', type: 'string'},
        {name: 'srSettlementDetlFirst.specs', mapping: 'specs', type: 'string'},
        {name: 'srSettlementDetlFirst.applyContent', mapping: 'applyContent', type: 'string'},
        {name: 'srSettlementDetlFirst.applyQty1', mapping: 'applyQty1', type: 'number'},
        {name: 'srSettlementDetlFirst.applyQty2', mapping: 'applyQty2', type: 'number'},
        {name: 'srSettlementDetlFirst.applyQty3', mapping: 'applyQty3', type: 'number'},
        {name: 'srSettlementDetlFirst.applyQty4', mapping: 'applyQty4', type: 'number'},
        {name: 'srSettlementDetlFirst.applyQty5', mapping: 'applyQty5', type: 'number'},
        {name: 'srSettlementDetlFirst.applyQty6', mapping: 'applyQty6', type: 'number'},
        {name: 'srSettlementDetlFirst.adjustContent', mapping: 'adjustContent', type: 'string'},
        {name: 'srSettlementDetlFirst.adjustQty1', mapping: 'adjustQty1', type: 'number'},
        {name: 'srSettlementDetlFirst.adjustQty2', mapping: 'adjustQty2', type: 'number'},
        {name: 'srSettlementDetlFirst.adjustQty3', mapping: 'adjustQty3', type: 'number'},
        {name: 'srSettlementDetlFirst.adjustQty4', mapping: 'adjustQty4', type: 'number'},
        {name: 'srSettlementDetlFirst.adjustQty5', mapping: 'adjustQty5', type: 'number'},
        {name: 'srSettlementDetlFirst.adjustQty6', mapping: 'adjustQty6', type: 'number'},
        {name: 'srSettlementDetlFirst.settleQty1', mapping: 'settleQty1', type: 'number'},
        {name: 'srSettlementDetlFirst.settleQty2', mapping: 'settleQty2', type: 'number'},
        {name: 'srSettlementDetlFirst.settleQty3', mapping: 'settleQty3', type: 'number'},
        {name: 'srSettlementDetlFirst.settleQty4', mapping: 'settleQty4', type: 'number'},
        {name: 'srSettlementDetlFirst.settleQty5', mapping: 'settleQty5', type: 'number'},
        {name: 'srSettlementDetlFirst.settleQty6', mapping: 'settleQty6', type: 'number'},
        {name: 'srSettlementDetlFirst.amount', mapping: 'amount', type: 'number'},
        {name: 'srSettlementDetlFirst.attachment', mapping: 'attachment', type: 'string'},
        {name: 'srSettlementDetlFirst.comment', mapping: 'comment', type: 'string'},
        {name: 'srSettlementDetlFirst.status', mapping: 'status', type: 'string'},
        {name: 'srSettlementDetlFirst.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'srSettlementDetlFirst.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'srSettlementDetlFirst.createTime', mapping: 'createTime', type: 'date'},
        {name: 'srSettlementDetlFirst.confirmAcc', mapping: 'confirmAcc', type: 'string'},
        {name: 'srSettlementDetlFirst.confirmName', mapping: 'confirmName', type: 'string'},
        {name: 'srSettlementDetlFirst.confirmTime', mapping: 'confirmTime', type: 'date'},
    ]
});