Ext.define('iFlat.model.xr.Benefit', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'benefit.id', mapping: 'id', type: 'string'},
        {name: 'benefit.month', mapping: 'month', type: 'date'},
        {name: 'benefit.dept', mapping: 'dept', type: 'string'},
        {name: 'benefit.teamCode', mapping: 'teamCode', type: 'string'},
        {name: 'benefit.team', mapping: 'team', type: 'string'},
        {name: 'benefit.workday', mapping: 'workday', type: 'number'},
        {name: 'benefit.manhour', mapping: 'manhour', type: 'number'},
        {name: 'benefit.personNum', mapping: 'personNum', type: 'number'},
        {name: 'benefit.workPersonTime', mapping: 'workPersonTime', type: 'number'},
        {name: 'benefit.waitPersonTime', mapping: 'waitPersonTime', type: 'number'},
        {name: 'benefit.casualInPersonTime', mapping: 'casualInPersonTime', type: 'number'},
        {name: 'benefit.casualOutPersonTime', mapping: 'casualOutPersonTime', type: 'number'},
        {name: 'benefit.salaryPersonNum', mapping: 'salaryPersonNum', type: 'number'},
        {name: 'benefit.averagePersonNum', mapping: 'averagePersonNum', type: 'number'},
        {name: 'benefit.laborExpense', mapping: 'laborExpense', type: 'number'},
        {name: 'benefit.quarterProjectBonus', mapping: 'quarterProjectBonus', type: 'number'},
        {name: 'benefit.waitSubsidy', mapping: 'waitSubsidy', type: 'number'},
        {name: 'benefit.springFestivalSubsidy', mapping: 'springFestivalSubsidy', type: 'number'},
        {name: 'benefit.springFestivalStable', mapping: 'springFestivalStable', type: 'number'},
        {name: 'benefit.dinnerSubsidy', mapping: 'dinnerSubsidy', type: 'number'},
        {name: 'benefit.temperatureSubsidy', mapping: 'temperatureSubsidy', type: 'number'},
        {name: 'benefit.incomeSum', mapping: 'incomeSum', type: 'number'},
        {name: 'benefit.payableSalary', mapping: 'payableSalary', type: 'number'},
        {name: 'benefit.rent', mapping: 'rent', type: 'number'},
        {name: 'benefit.dinnerSelf', mapping: 'dinnerSelf', type: 'number'},
        {name: 'benefit.insurance', mapping: 'insurance', type: 'number'},
        {name: 'benefit.material', mapping: 'material', type: 'number'},
        {name: 'benefit.taxes', mapping: 'taxes', type: 'number'},
        {name: 'benefit.expenseSum', mapping: 'expenseSum', type: 'number'},
        {name: 'benefit.profits', mapping: 'profits', type: 'number'},
        {name: 'benefit.salaryPercent', mapping: 'salaryPercent', type: 'number'},
        {name: 'benefit.productionPer', mapping: 'productionPer', type: 'number'},
        {name: 'benefit.salaryPerFull', mapping: 'salaryPerFull', type: 'number'},
        {name: 'benefit.salaryPerAct', mapping: 'salaryPerAct', type: 'number'},
        {name: 'benefit.comment', mapping: 'comment', type: 'string'},
        {name: 'benefit.fromDate', mapping: 'fromDate', type: 'date'},
        {name: 'benefit.todate', mapping: 'toDate', type: 'date'},
    ]
});