Ext.define('iFlat.model.xr.Salary', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'salary.id', mapping: 'id', type: 'string'},
        {name: 'salary.month', mapping: 'month', type: 'date'},
        {name: 'salary.teamCode', mapping: 'teamCode', type: 'string'},
        {name: 'salary.team', mapping: 'team', type: 'string'},
        {name: 'salary.idCardNo', mapping: 'idCardNo', type: 'string'},
        {name: 'salary.name', mapping: 'name', type: 'string'},
        {name: 'salary.bank', mapping: 'bank', type: 'string'},
        {name: 'salary.account', mapping: 'account', type: 'string'},
        {name: 'salary.workday', mapping: 'workday', type: 'number'},
        {name: 'salary.workHour', mapping: 'workHour', type: 'number'},
        {name: 'salary.waitHour', mapping: 'waitHour', type: 'number'},
        {name: 'salary.overtimeHour', mapping: 'overtimeHour', type: 'number'},
        {name: 'salary.hourPrice', mapping: 'hourPrice', type: 'number'},
        {name: 'salary.dayPrice', mapping: 'dayPrice', type: 'number'},
        {name: 'salary.hourOfDay', mapping: 'hourOfDay', type: 'number', defaultValue: 8},
        {name: 'salary.waitSubsidy', mapping: 'waitSubsidy', type: 'number'},
        {name: 'salary.monthPrice', mapping: 'monthPrice', type: 'number'},
        {name: 'salary.prepay', mapping: 'prepay', type: 'number'},
        {name: 'salary.deductionOfCheck', mapping: 'deductionOfCheck', type: 'number'},
        {name: 'salary.overtimeAmount', mapping: 'overtimeAmount', type: 'number'},
        {name: 'salary.otherSubsidy', mapping: 'otherSubsidy', type: 'number'},
        {name: 'salary.springFestivalSubsidy', mapping: 'springFestivalSubsidy', type: 'number'},
        {name: 'salary.bonusAmount', mapping: 'bonusAmount', type: 'number'},
        {name: 'salary.payableAmount', mapping: 'payableAmount', type: 'number'},
        {name: 'salary.retentionAmount', mapping: 'retentionAmount', type: 'number'},
        {name: 'salary.supplementaryAmount', mapping: 'supplementaryAmount', type: 'number'},
        {name: 'salary.dinnerAmount', mapping: 'dinnerAmount', type: 'number'},
        {name: 'salary.loanAmount', mapping: 'loanAmount', type: 'number'},
        {name: 'salary.fineAmount', mapping: 'fineAmount', type: 'number'},
        {name: 'salary.otherDeductAmount', mapping: 'otherDeductAmount', type: 'number'},
        {name: 'salary.otherFee', mapping: 'otherFee', type: 'number'},
        {name: 'salary.actualAmount', mapping: 'actualAmount', type: 'number'},
        {name: 'salary.comment', mapping: 'comment', type: 'string'},
        {name: 'salary.fromDate', mapping: 'fromDate', type: 'date'},
        {name: 'salary.todate', mapping: 'toDate', type: 'date'},
    ]
});