Ext.define('iFlat.model.xr.SrSettlement', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'xrSrSettlement.id', mapping: 'id', type: 'string'},
        {name: 'xrSrSettlement.progress', mapping: 'progress', type: 'number'},
        {name: 'xrSrSettlement.projNo', mapping: 'projNo', type: 'string'},
        {name: 'xrSrSettlement.projName', mapping: 'projName', type: 'string'},
        {name: 'xrSrSettlement.deptCode', mapping: 'deptCode', type: 'string'},
        {name: 'xrSrSettlement.dept', mapping: 'dept', type: 'string'},
        {name: 'xrSrSettlement.teamCode', mapping: 'teamCode', type: 'string'},
        {name: 'xrSrSettlement.team', mapping: 'team', type: 'string'},
        {name: 'xrSrSettlement.isOutwork', mapping: 'isOutwork', type: 'boolean'},
        {name: 'xrSrSettlement.amountFirst', mapping: 'amountFirst', type: 'number'},
        {name: 'xrSrSettlement.amountSecond', mapping: 'amountSecond', type: 'number'},
        {name: 'xrSrSettlement.discountRate', mapping: 'discountRate', type: 'number'},
        {name: 'xrSrSettlement.amountWithDiscount', mapping: 'amountWithDiscount', type: 'number'},
        {name: 'xrSrSettlement.amountDiff', mapping: 'amountDiff', type: 'number'},
        {name: 'xrSrSettlement.attachment', mapping: 'attachment', type: 'string'},
        {name: 'xrSrSettlement.balApplAtt', mapping: 'balApplAtt', type: 'string'},
        {name: 'xrSrSettlement.comment', mapping: 'comment', type: 'string'},
        {name: 'xrSrSettlement.status', mapping: 'status', type: 'string'},
        {name: 'xrSrSettlement.isQuota', mapping: 'isQuota', type: 'boolean'},
        {name: 'xrSrSettlement.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'xrSrSettlement.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'xrSrSettlement.createTime', mapping: 'createTime', type: 'date'},
        {name: 'xrSrSettlement.teamAcc', mapping: 'teamAcc', type: 'string'},
        {name: 'xrSrSettlement.teamName', mapping: 'teamName', type: 'string'},
        {name: 'xrSrSettlement.score', mapping: 'score', defaultValue: 100, type: 'number'},
        {name: 'xrSrSettlement.opinion', mapping: 'opinion', type: 'string'},
        {name: 'xrSrSettlement.settFirstAcc', mapping: 'settFirstAcc', type: 'string'},
        {name: 'xrSrSettlement.settFirstName', mapping: 'settFirstName', type: 'string'},
        {name: 'xrSrSettlement.settFirstTime', mapping: 'settFirstTime', type: 'date'},
        {name: 'xrSrSettlement.settlementTime', mapping: 'settlementTime', type: 'date'},
        {name: 'xrSrSettlement.discountRate', mapping: 'discountRate', type: 'number'},
        {name: 'xrSrSettlement.amountWithDiscount', mapping: 'amountWithDiscount', type: 'number'},
    ]
});