CREATE TABLE WipSrOutsource
(
    id CHAR(36),
    projNo VARCHAR(30),
    projName VARCHAR(200),
    projType VARCHAR(100),
    dept VARCHAR(50),
    type VARCHAR(20),
    capitalSource VARCHAR(30),
    matSource VARCHAR(30),
    tod DATETIME,
    hasBluePrint BIT,
    hasSample BIT,
    ownerAppoint BIT,
    aplAtt VARCHAR(4000),
    aplComment VARCHAR(4000),
    bidNo VARCHAR(50),
    bidType VARCHAR(30),
    bidAtt VARCHAR(4000),
    vendor VARCHAR(400),
    vendorType VARCHAR(100),
    bidAmountFirst DECIMAL(18, 2),
    bidAmountSecond DECIMAL(18, 2),
    bidComment VARCHAR(4000),
    saleOpinion VARCHAR(4000),
    contNo VARCHAR(50),
    contDate DATETIME,
    contAmount DECIMAL(18, 2),
    contAtt VARCHAR(4000),
    conComment VARCHAR(4000),
    finishTime DATETIME,
    otReason VARCHAR(2000),
    inspResult VARCHAR(30),
    inspComment VARCHAR(4000),
    inspAtt VARCHAR(4000),
    settAmountFirst DECIMAL(18, 2),
    settAmountSecond DECIMAL(18, 2),
    settComment VARCHAR(4000),
    settAtt VARCHAR(4000),
    saleComment VARCHAR(4000),
    creatorAcc VARCHAR(20),
    creatorName VARCHAR(100),
    createTime DATETIME,
    auditorAcc VARCHAR(20),
    auditorName VARCHAR(100),
    signorAcc VARCHAR(20),
    signorName VARCHAR(100),
    operatorAcc VARCHAR(20),
    operatorName VARCHAR(100),
    saleAcc VARCHAR(20),
    saleName VARCHAR(100),
    qcAcc VARCHAR(20),
    qcName VARCHAR(100),
    bdDirectorAcc VARCHAR(20),
    bdDirectorName VARCHAR(100),
    completeTime DATETIME,
)