CREATE TABLE XrSrSettlement
(
    id VARCHAR(100),
    progress DECIMAL(18, 2),
    projNo VARCHAR(100),
    projName VARCHAR(100),
    dept VARCHAR(100),
    team VARCHAR(100),
    isOutwork BIT,
    amountFirst DECIMAL(18, 2),
    amountSecond DECIMAL(18, 2),
    attachment VARCHAR(100),
    comment VARCHAR(100),
    status VARCHAR(100),
    isQuota BIT,
    creatorAcc VARCHAR(100),
    creatorName VARCHAR(100),
    createTime DATETIME,
    teamAcc VARCHAR(100),
    teamName VARCHAR(100),
    score DECIMAL(18, 2),
    opinion VARCHAR(100),
    settFirstAcc VARCHAR(100),
    settFirstName VARCHAR(100),
    settFirstTime DATETIME,
    settlementTime DATETIME,
)