CREATE TABLE XrSrSettlementDetl
(
    id VARCHAR(100),
    pid VARCHAR(100),
    code VARCHAR(100),
    category VARCHAR(100),
    isQuota BIT,
    specs VARCHAR(100),
    unit VARCHAR(100),
    applyContent VARCHAR(100),
    applyQty DECIMAL(18, 2),
    adjustContent VARCHAR(100),
    adjustQty DECIMAL(18, 2),
    quota DECIMAL(18, 2),
    degree DECIMAL(18, 2),
    priceFirst DECIMAL(18, 2),
    amountFirst DECIMAL(18, 2),
    priceSecond DECIMAL(18, 2),
    amountSecond DECIMAL(18, 2),
    comment VARCHAR(100),
    creatorAcc VARCHAR(100),
    creatorName VARCHAR(100),
    createTime DATETIME,
)