CREATE TABLE XrTrSettlement
(
    id CHAR(36),
    projNo VARCHAR(100),
    projName VARCHAR(200),
    dept VARCHAR(100),
    team VARCHAR(200),
    reason VARCHAR(1000),
    isOutwork BIT,
    amountFirst DECIMAL(18, 2),
    amountSecond DECIMAL(18, 2),
    amountDiff DECIMAL(18, 2),
    attachment VARCHAR(4000),
    balApplAtt VARCHAR(4000),
    comment VARCHAR(2000),
    status VARCHAR(50),
    isQuota BIT,
    creatorAcc VARCHAR(100),
    creatorName VARCHAR(100),
    creatorDept VARCHAR(100),
    createTime DATETIME,
    teamAcc VARCHAR(100),
    teamName VARCHAR(100),
    score DECIMAL(18, 2),
    opinion VARCHAR(2000),
    settFirstAcc VARCHAR(100),
    settFirstName VARCHAR(100),
    settFirstTime DATETIME,
    settlementTime DATETIME,
    discountRate DECIMAL(18, 2),
    amountWithDiscount DECIMAL(18, 2),
)