Ext.define('iFlat.model.ss.FiveS', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'fiveS.id', mapping: 'id', type: 'string'},
        {name: 'fiveS.date', mapping: 'date', type: 'date'},
        {name: 'fiveS.time', mapping: 'time', type: 'string'},
        {name: 'fiveS.funcDept', mapping: 'funcDept', type: 'string'},
        {name: 'fiveS.areaType', mapping: 'areaType', type: 'string'},
        {name: 'fiveS.area', mapping: 'area', type: 'string'},
        {name: 'fiveS.code', mapping: 'code', type: 'string'},
        {name: 'fiveS.otherArea', mapping: 'otherArea', type: 'string'},
        {name: 'fiveS.projNo', mapping: 'projNo', type: 'string'},
        {name: 'fiveS.projName', mapping: 'projName', type: 'string'},
        {name: 'fiveS.region', mapping: 'region', type: 'string'},
        {name: 'fiveS.belongDept', mapping: 'belongDept', type: 'string'},
        {name: 'fiveS.regionPersonAcc', mapping: 'regionPersonAcc', type: 'string'},
        {name: 'fiveS.regionPersonName', mapping: 'regionPersonName', type: 'string'},
        {name: 'fiveS.fsType', mapping: 'fsType', type: 'string'},
        {name: 'fiveS.fsDescription', mapping: 'fsDescription', type: 'string'},
        {name: 'fiveS.attachment', mapping: 'attachment', type: 'string'},
        {name: 'fiveS.dept', mapping: 'dept', type: 'string'},
        {name: 'fiveS.team', mapping: 'team', type: 'string'},
        {name: 'fiveS.personAcc', mapping: 'personAcc', type: 'string'},
        {name: 'fiveS.personName', mapping: 'personName', type: 'string'},
        {name: 'fiveS.feedback', mapping: 'feedback', type: 'string'},
        {name: 'fiveS.rectifyTime', mapping: 'rectifyTime', type: 'date'},
        {name: 'fiveS.rectifyAtt', mapping: 'rectifyAtt', type: 'string'},
        {name: 'fiveS.comment', mapping: 'comment', type: 'string'},
        {name: 'fiveS.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'fiveS.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'fiveS.creatorDept', mapping: 'creatorDept', type: 'string'},
        {name: 'fiveS.createTime', mapping: 'createTime', type: 'date'},
        {name: 'fiveS.score', mapping: 'score', type: 'number'},
        {name: 'fiveS.amount', mapping: 'amount', type: 'number'},
        {name: 'fiveS.issuer', mapping: 'issuer', type: 'string'},
        {name: 'fiveS.issueDept', mapping: 'issueDept', type: 'string'},
        {name: 'fiveS.fromDate', mapping: 'fromDate', type: 'date'},
        {name: 'fiveS.toDate', mapping: 'toDate', type: 'date'},
    ]
});