Ext.define('iFlat.model.ss.PotentialHazard', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'potentialHazard.id', mapping: 'id', type: 'string'},
        {name: 'potentialHazard.date', mapping: 'date', type: 'date'},
        {name: 'potentialHazard.time', mapping: 'time', type: 'string'},
        {name: 'potentialHazard.riskLvl', mapping: 'riskLvl', type: 'string'},
        {name: 'potentialHazard.phType', mapping: 'phType', type: 'string'},
        {name: 'potentialHazard.phCode', mapping: 'phCode', type: 'string'},
        {name: 'potentialHazard.dept', mapping: 'dept', type: 'string'},
        {name: 'potentialHazard.team', mapping: 'team', type: 'string'},
        {name: 'potentialHazard.groupName', mapping: 'groupName', type: 'string'},
        {name: 'potentialHazard.title', mapping: 'title', type: 'string'},
        {name: 'potentialHazard.personAcc', mapping: 'personAcc', type: 'string'},
        {name: 'potentialHazard.personName', mapping: 'personName', type: 'string'},
        {name: 'potentialHazard.age', mapping: 'age', type: 'number'},
        {name: 'potentialHazard.seniority', mapping: 'seniority', type: 'number'},
        {name: 'potentialHazard.sex', mapping: 'sex', type: 'string'},
        {name: 'potentialHazard.projNo', mapping: 'projNo', type: 'string'},
        {name: 'potentialHazard.projName', mapping: 'projName', type: 'string'},
        {name: 'potentialHazard.area', mapping: 'area', type: 'string'},
        {name: 'potentialHazard.position', mapping: 'position', type: 'string'},
        {name: 'potentialHazard.description', mapping: 'description', type: 'string'},
        {name: 'potentialHazard.measure', mapping: 'measure', type: 'string'},
        {name: 'potentialHazard.deadline', mapping: 'deadline', type: 'string'},
        {name: 'potentialHazard.feedback', mapping: 'feedback', type: 'string'},
        {name: 'potentialHazard.amount', mapping: 'amount', type: 'number'},
        {name: 'potentialHazard.busiDivision', mapping: 'busiDivision', type: 'string'},
        {name: 'potentialHazard.projMgr', mapping: 'projMgr', type: 'string'},
        {name: 'potentialHazard.profMgr', mapping: 'profMgr', type: 'string'},
        {name: 'potentialHazard.workMgr', mapping: 'workMgr', type: 'string'},
        {name: 'potentialHazard.teamLeader', mapping: 'teamLeader', type: 'string'},
        {name: 'potentialHazard.posiMgr', mapping: 'posiMgr', type: 'string'},
        {name: 'potentialHazard.score', mapping: 'score', type: 'number'},
        {name: 'potentialHazard.attachment', mapping: 'attachment', type: 'string'},
        {name: 'potentialHazard.comment', mapping: 'comment', type: 'string'},
        {name: 'potentialHazard.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'potentialHazard.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'potentialHazard.creatorDept', mapping: 'creatorDept', type: 'string'},
        {name: 'potentialHazard.createTime', mapping: 'createTime', type: 'date'},
        {name: 'potentialHazard.issuer', mapping: 'issuer', type: 'string'},
        {name: 'potentialHazard.issueDept', mapping: 'issueDept', type: 'string'},
        {name: 'potentialHazard.fromDate', mapping: 'fromDate', type: 'date'},
        {name: 'potentialHazard.toDate', mapping: 'toDate', type: 'date'},
    ]
});