Ext.define('iFlat.model.ss.ViolateRegulation', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'violateRegulation.id', mapping: 'id', type: 'string'},
        {name: 'violateRegulation.time', mapping: 'time', type: 'date'},
        {name: 'violateRegulation.riskLvl', mapping: 'riskLvl', type: 'string'},
        {name: 'violateRegulation.code', mapping: 'code', type: 'string'},
        {name: 'violateRegulation.dept', mapping: 'dept', type: 'string'},
        {name: 'violateRegulation.team', mapping: 'team', type: 'string'},
        {name: 'violateRegulation.groupName', mapping: 'groupName', type: 'string'},
        {name: 'violateRegulation.title', mapping: 'title', type: 'string'},
        {name: 'violateRegulation.personAcc', mapping: 'personAcc', type: 'string'},
        {name: 'violateRegulation.personName', mapping: 'personName', type: 'string'},
        {name: 'violateRegulation.age', mapping: 'age', type: 'number'},
        {name: 'violateRegulation.seniority', mapping: 'seniority', type: 'number'},
        {name: 'violateRegulation.sex', mapping: 'sex', type: 'string'},
        {name: 'violateRegulation.projNo', mapping: 'projNo', type: 'string'},
        {name: 'violateRegulation.projName', mapping: 'projName', type: 'string'},
        {name: 'violateRegulation.area', mapping: 'area', type: 'string'},
        {name: 'violateRegulation.position', mapping: 'position', type: 'string'},
        {name: 'violateRegulation.description', mapping: 'description', type: 'string'},
        {name: 'violateRegulation.measure', mapping: 'measure', type: 'string'},
        {name: 'violateRegulation.feedback', mapping: 'feedback', type: 'string'},
        {name: 'violateRegulation.amount', mapping: 'amount', type: 'number'},
        {name: 'violateRegulation.busiDivision', mapping: 'busiDivision', type: 'string'},
        {name: 'violateRegulation.projMgr', mapping: 'projMgr', type: 'string'},
        {name: 'violateRegulation.profMgr', mapping: 'profMgr', type: 'string'},
        {name: 'violateRegulation.workMgr', mapping: 'workMgr', type: 'string'},
        {name: 'violateRegulation.teamLeader', mapping: 'teamLeader', type: 'string'},
        {name: 'violateRegulation.posiMgr', mapping: 'posiMgr', type: 'string'},
        {name: 'violateRegulation.score', mapping: 'score', type: 'number'},
        {name: 'violateRegulation.training', mapping: 'training', type: 'string'},
        {name: 'violateRegulation.trainingEff', mapping: 'trainingEff', type: 'string'},
        {name: 'violateRegulation.attachment', mapping: 'attachment', type: 'string'},
        {name: 'violateRegulation.comment', mapping: 'comment', type: 'string'},
        {name: 'violateRegulation.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'violateRegulation.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'violateRegulation.creatorDept', mapping: 'creatorDept', type: 'string'},
        {name: 'violateRegulation.createTime', mapping: 'createTime', type: 'date'},
        {name: 'violateRegulation.fromDate', mapping: 'fromDate', type: 'date'},
        {name: 'violateRegulation.toDate', mapping: 'toDate', type: 'date'},
    ]
});