Ext.define('iFlat.model.wip.SrOutsourceView', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'srOutsourceView.id', mapping: 'id', type: 'string'},
        {name: 'srOutsourceView.name', mapping: 'name', type: 'string'},
        {name: 'srOutsourceView.projNo', mapping: 'projNo', type: 'string'},
        {name: 'srOutsourceView.projName', mapping: 'projName', type: 'string'},
        {name: 'srOutsourceView.projType', mapping: 'projType', type: 'string'},
        {name: 'srOutsourceView.dept', mapping: 'dept', type: 'string'},
        {name: 'srOutsourceView.type', mapping: 'type', type: 'string'},
        {name: 'srOutsourceView.type1', mapping: 'type1', type: 'boolean'},
        {name: 'srOutsourceView.type2', mapping: 'type2', type: 'boolean'},
        {name: 'srOutsourceView.type3', mapping: 'type3', type: 'boolean'},
        {name: 'srOutsourceView.capitalSource', mapping: 'capitalSource', type: 'string'},
        {name: 'srOutsourceView.matSource', mapping: 'matSource', type: 'string'},
        {name: 'srOutsourceView.tod', mapping: 'tod', type: 'date'},
        {name: 'srOutsourceView.hasBluePrint', mapping: 'hasBluePrint', type: 'boolean'},
        {name: 'srOutsourceView.hasSample', mapping: 'hasSample', type: 'boolean'},
        {name: 'srOutsourceView.ownerAppoint', mapping: 'ownerAppoint', type: 'boolean'},
        {name: 'srOutsourceView.aplAtt', mapping: 'aplAtt', type: 'string'},
        {name: 'srOutsourceView.aplComment', mapping: 'aplComment', type: 'string'},
        {name: 'srOutsourceView.bidNo', mapping: 'bidNo', type: 'string'},
        {name: 'srOutsourceView.bidType', mapping: 'bidType', type: 'string'},
        {name: 'srOutsourceView.bidType1', mapping: 'bidType1', type: 'boolean'},
        {name: 'srOutsourceView.bidType2', mapping: 'bidType2', type: 'boolean'},
        {name: 'srOutsourceView.bidType3', mapping: 'bidType3', type: 'boolean'},
        {name: 'srOutsourceView.bidType4', mapping: 'bidType4', type: 'boolean'},
        {name: 'srOutsourceView.bidType5', mapping: 'bidType5', type: 'boolean'},
        {name: 'srOutsourceView.bidAtt', mapping: 'bidAtt', type: 'string'},
        {name: 'srOutsourceView.vendor', mapping: 'vendor', type: 'string'},
        {name: 'srOutsourceView.vendorType', mapping: 'vendorType', type: 'string'},
        {name: 'srOutsourceView.vendorType1', mapping: 'vendorType1', type: 'boolean'},
        {name: 'srOutsourceView.vendorType2', mapping: 'vendorType2', type: 'boolean'},
        {name: 'srOutsourceView.vendorType3', mapping: 'vendorType3', type: 'boolean'},
        {name: 'srOutsourceView.bidAmountFirst', mapping: 'bidAmountFirst', type: 'number'},
        {name: 'srOutsourceView.bidAmountSecond', mapping: 'bidAmountSecond', type: 'number'},
        {name: 'srOutsourceView.bidAmountDiff', mapping: 'bidAmountDiff', type: 'number'},
        {name: 'srOutsourceView.bidComment', mapping: 'bidComment', type: 'string'},
        {name: 'srOutsourceView.saleOpinion', mapping: 'saleOpinion', type: 'string'},
        {name: 'srOutsourceView.contNo', mapping: 'contNo', type: 'string'},
        {name: 'srOutsourceView.contDate', mapping: 'contDate', type: 'date'},
        {name: 'srOutsourceView.contAmount', mapping: 'contAmount', type: 'number'},
        {name: 'srOutsourceView.contAtt', mapping: 'contAtt', type: 'string'},
        {name: 'srOutsourceView.conComment', mapping: 'conComment', type: 'string'},
        {name: 'srOutsourceView.finishTime', mapping: 'finishTime', type: 'date'},
        {name: 'srOutsourceView.overtime', mapping: 'overtime', type: 'boolean'},
        {name: 'srOutsourceView.otReason', mapping: 'otReason', type: 'string'},
        {name: 'srOutsourceView.inspResult', mapping: 'inspResult', type: 'string'},
        {name: 'srOutsourceView.inspComment', mapping: 'inspComment', type: 'string'},
        {name: 'srOutsourceView.inspAtt', mapping: 'inspAtt', type: 'string'},
        {name: 'srOutsourceView.settAmountFirst', mapping: 'settAmountFirst', type: 'number'},
        {name: 'srOutsourceView.settAmountSecond', mapping: 'settAmountSecond', type: 'number'},
        {name: 'srOutsourceView.settAmountDiff', mapping: 'settAmountDiff', type: 'number'},
        {name: 'srOutsourceView.settComment', mapping: 'settComment', type: 'string'},
        {name: 'srOutsourceView.settAtt', mapping: 'settAtt', type: 'string'},
        {name: 'srOutsourceView.saleReaudit', mapping: 'saleReaudit', type: 'boolean'},
        {name: 'srOutsourceView.saleComment', mapping: 'saleComment', type: 'string'},
        {name: 'srOutsourceView.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'srOutsourceView.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'srOutsourceView.createTime', mapping: 'createTime', type: 'date'},
        {name: 'srOutsourceView.auditorAcc', mapping: 'auditorAcc', type: 'string'},
        {name: 'srOutsourceView.auditorName', mapping: 'auditorName', type: 'string'},
        {name: 'srOutsourceView.signorAcc', mapping: 'signorAcc', type: 'string'},
        {name: 'srOutsourceView.signorName', mapping: 'signorName', type: 'string'},
        {name: 'srOutsourceView.operatorAcc', mapping: 'operatorAcc', type: 'string'},
        {name: 'srOutsourceView.operatorName', mapping: 'operatorName', type: 'string'},
        {name: 'srOutsourceView.saleAcc', mapping: 'saleAcc', type: 'string'},
        {name: 'srOutsourceView.saleName', mapping: 'saleName', type: 'string'},
        {name: 'srOutsourceView.qcAcc', mapping: 'qcAcc', type: 'string'},
        {name: 'srOutsourceView.qcName', mapping: 'qcName', type: 'string'},
        {name: 'srOutsourceView.bdDirectorAcc', mapping: 'bdDirectorAcc', type: 'string'},
        {name: 'srOutsourceView.bdDirectorName', mapping: 'bdDirectorName', type: 'string'},
        {name: 'srOutsourceView.completeTime', mapping: 'completeTime', type: 'date'},
        {name: 'srOutsourceView.status', mapping: 'status', type: 'string'},
        {name: 'srOutsourceView.pid', mapping: 'pid', type: 'string'},
        {name: 'srOutsourceView.content', mapping: 'content', type: 'string'},
        {name: 'srOutsourceView.specs', mapping: 'specs', type: 'string'},
        {name: 'srOutsourceView.unit', mapping: 'unit', type: 'string'},
        {name: 'srOutsourceView.qty', mapping: 'qty', type: 'number'},
        {name: 'srOutsourceView.detlComment', mapping: 'detlComment', type: 'string'},
        {name: 'srOutsourceView.fromDate', mapping: 'fromDate', type: 'date'},
        {name: 'srOutsourceView.toDate', mapping: 'toDate', type: 'date'},
        {name: 'srOutsourceView.targetCst', mapping: 'targetCst', type: 'number'},
        {name: 'srOutsourceView.bidLowest', mapping: 'bidLowest', type: 'boolean'},
        {
            name: 'srOutsourceView.retention',
            mapping: function (data) {
                if (!Flat.util.isEmpty(data['contNo'])) {
                    return '有';
                } else {
                    return '';
                }
            },
            type: 'string'
        },
    ]
});