Ext.define('iFlat.model.hr.Credit', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'credit.id', mapping: 'id', type: 'string'},
        {name: 'credit.type', mapping: 'type', type: 'string'},
        {name: 'credit.date', mapping: 'date', type: 'date'},
        {name: 'credit.projNo', mapping: 'projNo', type: 'string'},
        {name: 'credit.projName', mapping: 'projName', type: 'string'},
        {name: 'credit.dept', mapping: 'dept', type: 'string'},
        {name: 'credit.team', mapping: 'team', type: 'string'},
        {name: 'credit.group', mapping: 'group', type: 'string'},
        {name: 'credit.personAcc', mapping: 'personAcc', type: 'string'},
        {name: 'credit.personName', mapping: 'personName', type: 'string'},
        {name: 'credit.description', mapping: 'description', type: 'string'},
        {name: 'credit.attachment', mapping: 'attachment', type: 'string'},
        {name: 'credit.amount', mapping: 'amount', type: 'number'},
        {name: 'credit.score', mapping: 'score', type: 'number'},
        {name: 'credit.comment', mapping: 'comment', type: 'string'},
        {name: 'credit.area', mapping: 'area', type: 'string'},
        {name: 'credit.areaMgr', mapping: 'areaMgr', type: 'string'},
        {name: 'credit.manager', mapping: 'manager', type: 'string'},
        {name: 'credit.groupMgr', mapping: 'groupMgr', type: 'string'},
        {name: 'credit.projMgr', mapping: 'projMgr', type: 'string'},
        {name: 'credit.profMgr', mapping: 'profMgr', type: 'string'},
        {name: 'credit.workMgr', mapping: 'workMgr', type: 'string'},
        {name: 'credit.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'credit.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'credit.creatorDept', mapping: 'creatorDept', type: 'string'},
        {name: 'credit.createTime', mapping: 'createTime', type: 'date'},
        {name: 'credit.fromDate', mapping: 'fromDate', type: 'date'},
        {name: 'credit.toDate', mapping: 'toDate', type: 'date'},
    ]
});