Ext.define('iFlat.model.report.wip.manhour.WoStatus', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'projNo', mapping: 'projNo', type: 'string'},
        {name: 'type', mapping: 'type', type: 'string'},
        {name: 'name', mapping: 'name', type: 'string'},
        {name: 'woNo', mapping: 'woNo', type: 'string'},
        {name: 'description', mapping: 'description', type: 'string'},
        {name: 'createTime', mapping: 'createTime', type: 'date'},
        {name: 'dept', mapping: 'dept', type: 'string'},
        {name: 'team', mapping: 'team', type: 'string'},
        {name: 'group', mapping: 'group', type: 'string'},
        {name: 'createUser', mapping: 'createUser', type: 'string'},
        {name: 'mgrConfirm', mapping: 'mgrConfirm', type: 'string'},
        {name: 'balConfirm', mapping: 'balConfirm', type: 'string'},
        {name: 'hasComplete', mapping: 'hasComplete', type: 'string'},
        {name: 'hasQuota', mapping: 'hasQuota', type: 'string'},
        {name: 'quota', mapping: 'quota', type: 'number'},
        {name: 'hasActual', mapping: 'hasActual', type: 'string'},
        {name: 'printed', mapping: 'printed', type: 'string'},
        {name: 'finalConfirm', mapping: 'finalConfirm', type: 'string'},
    ],
})
