Ext.define('iFlat.model.pam.MonthlyWork', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'monthlyWork.id', mapping: 'id', type: 'string'},
        {name: 'monthlyWork.month', mapping: 'month', type: 'date'},
        {name: 'monthlyWork.pbName', mapping: 'pbName', type: 'string'},
        {name: 'monthlyWork.confBig', mapping: 'confBig', type: 'string'},
        {name: 'monthlyWork.confCom', mapping: 'confCom', type: 'string'},
        {name: 'monthlyWork.confGroup', mapping: 'confGroup', type: 'string'},
        {name: 'monthlyWork.confClass', mapping: 'confClass', type: 'string'},
        {name: 'monthlyWork.confContent', mapping: 'confContent', type: 'string'},
        {name: 'monthlyWork.devApplyNum', mapping: 'devApplyNum', type: 'number'},
        {name: 'monthlyWork.devApplyNumSum', mapping: 'devApplyNumSum', type: 'number'},
        {name: 'monthlyWork.devActivistNum', mapping: 'devActivistNum', type: 'number'},
        {name: 'monthlyWork.devActivistNumSum', mapping: 'devActivistNumSum', type: 'number'},
        {name: 'monthlyWork.devCandidateNum', mapping: 'devCandidateNum', type: 'number'},
        {name: 'monthlyWork.devFullMemberNum', mapping: 'devFullMemberNum', type: 'number'},
        {name: 'monthlyWork.tmIsStable', mapping: 'tmIsStable', type: 'boolean'},
        {name: 'monthlyWork.tmHasPlan', mapping: 'tmHasPlan', type: 'boolean'},
        {name: 'monthlyWork.tmMeasure', mapping: 'tmMeasure', type: 'string'},
        {name: 'monthlyWork.mbStableMeasure', mapping: 'mbStableMeasure', type: 'string'},
        {name: 'monthlyWork.mbFocus', mapping: 'mbFocus', type: 'string'},
        {name: 'monthlyWork.mbProblem', mapping: 'mbProblem', type: 'string'},
        {name: 'monthlyWork.scMeasure', mapping: 'scMeasure', type: 'string'},
        {name: 'monthlyWork.aiSituation', mapping: 'aiSituation', type: 'string'},
        {name: 'monthlyWork.suMassWork', mapping: 'suMassWork', type: 'string'},
        {name: 'monthlyWork.seSubject', mapping: 'seSubject', type: 'string'},
        {name: 'monthlyWork.seEffect', mapping: 'seEffect', type: 'string'},
        {name: 'monthlyWork.mpWork', mapping: 'mpWork', type: 'string'},
        {name: 'monthlyWork.wiLightspot', mapping: 'wiLightspot', type: 'string'},
        {name: 'monthlyWork.attachment', mapping: 'attachment', type: 'string'},
        {name: 'monthlyWork.status', mapping: 'status', type: 'string'},
        {name: 'monthlyWork.creatorAcc', mapping: 'creatorAcc', type: 'string'},
        {name: 'monthlyWork.creatorName', mapping: 'creatorName', type: 'string'},
        {name: 'monthlyWork.createrTime', mapping: 'createrTime', type: 'date'},
    ]
});