Ext.define('iFlat.model.system.AuthDuplicateModule', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id', mapping: 'id', type: 'string'},
        {name: 'parentId', mapping: 'parentId', type: 'string'},
        {name: 'text', mapping: 'text', type: 'string'},
        {name: 'expanded', mapping: 'expanded', type: 'boolean'},
        {name: 'leaf', mapping: 'leaf', type: 'boolean'},
        {name: 'nodeId', mapping: 'nodeId', type: 'string'},
        {name: 'nodeName', mapping: 'nodeName', type: 'string'},
        {name: 'moduleName', mapping: 'moduleName', type: 'string'},
        {name: 'parentNodeId', mapping: 'parentNodeId', type: 'string'},
        {name: 'aweIcon', mapping: 'aweIcon', type: 'string'},
        {name: 'sequence', mapping: 'sequence', type: 'string'},
        {name: 'dbInstance', mapping: 'dbInstance', type: 'string'},
        {name: 'dbName', mapping: 'dbName', type: 'string'},
        {name: 'tableList', mapping: 'tableList', type: 'string'},
        {name: 'nameSpace', mapping: 'nameSpace', type: 'string'},
        {name: 'viewName', mapping: 'viewName', type: 'string'},
        {name: 'controller', mapping: 'controller', type: 'string'},
        {name: 'url', mapping: 'url', type: 'string'},
        {name: 'status', mapping: 'status', type: 'boolean'},
        {name: 'amId', mapping: 'amId', type: 'string'},
        {name: 'roleId', mapping: 'roleId', type: 'string'},
        {name: 'account', mapping: 'account', type: 'string'},
        {name: 'amStatus', mapping: 'amStatus', type: 'boolean', defaultValue: false},
        {name: 'aoStatus', mapping: 'aoStatus', type: 'boolean', defaultValue: false},
        {name: 'adStatus', mapping: 'adStatus', type: 'boolean', defaultValue: false},
        {name: 'checked', type: 'boolean', defaultValue: false}
    ],
});